backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

locale: cs

collections:
  - name: blog
    label: Aktuality
    label_singular: Příspěvek
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Titulek, name: titulek, widget: string }
      - { label: Datum, name: datum, widget: datetime, format: "YYYY-MM-DD", date_format: "DD.MM.YYYY", time_format: false }
      - label: Kategorie
        name: kategorie
        widget: select
        options:
          - { label: Aktivizace, value: Aktivizace }
          - { label: Péče, value: Péče }
          - { label: Terapie, value: Terapie }
          - { label: Události, value: Události }
          - { label: Pro rodiny, value: Pro rodiny }
          - { label: Přijetí, value: Přijetí }
      - { label: Perex, name: perex, widget: text }
      - { label: Obsah, name: body, widget: markdown }
      - { label: Náhledový obrázek, name: nahledovyObrazek, widget: image, required: false }
